<?php

return [
    'DUBIZZLE_WHATSAPP' => 'UC_NUP3WI',
    'BAYUT_WHATSAPP' => 'UC_DPPLAR',
    'SECONDARY_PIPELINE_ID' => 5,
    'LISTINGS_ENTITY_TYPE_ID' => 1040,
    'DEFAULT_RESPONSIBLE_PERSON_ID' => 146, // Alyssa Ashley Erise
];
